### ISSUE TITLE
IFRT tracking issue

### ISSUE THREAD

**Issue by mofeing** [EnzymeAD/Reactant.jl#176]
Based on https://github.com/pytorch/xla/blob/master/torch_xla/csrc/runtime/ifrt_computation_client.h, we might be interested in implementing some functions similar to the following C++ methods in ReactantExtra:

- [ ] From `IfrtComputationClient`
  - [ ] [`CreateDataPlaceholder`](https://github.com/pytorch/xla/blob/07d0823f2c33e83673787d53dc4c3e5bdf292449/torch_xla/csrc/runtime/ifrt_computation_client.cc#L187-L193)
  - [ ] [`GetDataShards`](https://github.com/pytorch/xla/blob/07d0823f2c33e83673787d53dc4c3e5bdf292449/torch_xla/csrc/runtime/ifrt_computation_client.cc#L195-L217), `GetDataShard`
  - [x] ~`GetPjRtBuffer`~ not implemented
  - [ ] [`Compile`](https://github.com/pytorch/xla/blob/07d0823f2c33e83673787d53dc4c3e5bdf292449/torch_xla/csrc/runtime/ifrt_computation_client.cc#L454-L515)
  - [ ] [`ExecuteComputation`](https://github.com/pytorch/xla/blob/07d0823f2c33e83673787d53dc4c3e5bdf292449/torch_xla/csrc/runtime/ifrt_computation_client.cc#L517-L524)
  - [ ] [`GetNumDevices`](https://github.com/pytorch/xla/blob/07d0823f2c33e83673787d53dc4c3e5bdf292449/torch_xla/csrc/runtime/ifrt_computation_client.cc#L620-L622)
  - [ ] [`GetDefaultDevice`](https://github.com/pytorch/xla/blob/07d0823f2c33e83673787d53dc4c3e5bdf292449/torch_xla/csrc/runtime/ifrt_computation_client.cc#L624-L626)
  - [ ] [`GetNumProcesses`](https://github.com/pytorch/xla/blob/07d0823f2c33e83673787d53dc4c3e5bdf292449/torch_xla/csrc/runtime/ifrt_computation_client.cc#L636-L643)
- [ ] Some functionality similar to `ComputationClient::Data` and `IfrtComputationClient::IfrtData`?

Also it might be interesting to get some ideas for abstracting both PjRt and IFRT structures into one common interface by looking to https://github.com/pytorch/xla/blob/master/torch_xla/csrc/runtime/computation_client.h

# Steps

1. Get some IFRT buffer object and move data in and out of it
2. Compile sth with this buffer

**Comment by mofeing** [comment]
@wsmoses A question about ReactantExtra's C-API: when the C++ API returns a `absl::StatusOr`, we sometimes unwrap the value manually, set an `error` inout argument and return a pointer; and other times we just call `xla::ValueOrThrow`. When should we use each?
