### ISSUE TITLE
Roadmap to v0.2

### ISSUE THREAD

**Issue by mofeing** [EnzymeAD/Reactant.jl#19]
- [x] #33
- [x] Support TPU #66 
- [ ] Fix asynchronous execution #9
- [x] Implement `@code_mlir` macro, like in [pangoraw/Coil.jl](https://github.com/pangoraw/Coil.jl) #17
- [ ] Implement missing derivative rules EnzymeAD/Enzyme-JAX#88
- [ ] Integrate into other frameworks
- [ ] #29
- [ ] #30
