### ISSUE TITLE
Tracking issue for shortcuts to MLIR ops

### ISSUE THREAD

**Issue by mofeing** [EnzymeAD/Reactant.jl#273]
- [ ] `stablehlo`
  - [x] `abs`
  - [x] `add`
  - [ ] `after_all`
  - [ ] `all_gather`
  - [ ] `all_reduce`
  - [ ] `all_to_all`
  - [x] `and`
  - [x] `atan2`
  - [ ] `batch_norm_grad`
  - [ ] `batch_norm_inference`
  - [ ] `batch_norm_training`
  - [ ] `bitcast_convert`
  - [ ] `broadcast_in_dim`
  - ~`broadcast`~ -> on deprecation process
  - [ ] `case`
  - [x] `cbrt`
  - [x] `ceil`
  - [x] `cholesky`
  - [x] `clamp`
  - [x] `count_leading_zeros`
  - [ ] `collective_broadcast`
  - [ ] `collective_permute`
  - [ ] `compare`
  - [x] `complex`
  - [ ] `composite`
  - [ ] `concatenate`
  - [x] `constant`
  - [ ] `convert`
  - [ ] `convolution`
  - [x] `cosine`
  - ~`create_token`~ -> on deprecation process
  - ~`cross_replica_sum`~ -> on deprecation process
  - [ ] `custom_call`
  - [x] `divide`
  - [ ] `dot_general`
  - ~`dot`~ -> on deprecation process
  - [ ] `dynamic_broadcast_in_dim`
  - [ ] `dynamic_conv`
  - [ ] `dynamic_gather`
  - [ ] `dynamic_iota`
  - [ ] `dynamic_pad`
  - [ ] `dynamic_reshape`
  - [ ] `dynamic_slice`
  - [ ] `dynamic_update_slice`
  - [ ] einsum -> on deprecation process, but used by `Tenet`
  - [x] `exponential`
  - [x] `exponential_minus_one`
  - [ ] `fft`
  - [x] `floor`
  - [ ] `gather`
  - [ ] `get_dimension_size`
  - ~`get_tuple_element`~ -> on deprecation process
  - [ ] `if_`
  - [x] `imag`
  - [ ] `infeed`
  - [ ] `iota`
  - [x] `is_finite`
  - [x] `log_plus_one`
  - [x] `log`
  - [x] `logistic`
  - ~`map`~ -> on deprecation process
  - [x] `maximum`
  - [x] `minimum`
  - [x] `multiply`
  - [x] `negate`
  - [x] `not`
  - [x] `optimization_barrier`
  - [x] `or`
  - [x] `outfeed`
  - [ ] `pad`
  - [x] `partition_id`
  - [x] `popcnt`
  - [x] `power`
  - ~`real_dynamic_slice`~ -> on deprecation process
  - [x] `real`
  - [ ] `recv`
  - [ ] `reduce`
  - [ ] `reduce_precision`
  - [ ] `reduce_scatter`
  - [ ] `reduce_window`
  - [x] `remainder`
  - [x] `replica_id`
  - [ ] `reshape`
  - [ ] `reverse`
  - [ ] `rng_bit_generator`
  - ~`rng`~ -> on deprecation process
  - [x] `round_nearest_even`
  - [x] `round_nearest_afz`
  - [x] `rsqrt`
  - [ ] `scatter`
  - [ ] `select_and_scatter`
  - [ ] `select`
  - [ ] `send`
  - [ ] `set_dimension_size`
  - [x] `shift_left`
  - [x] `shift_right_arithmetic`
  - [x] `shift_right_logical`
  - [x] `sign`
  - [x] `sine`
  - [ ] `slice`
  - [ ] `sort`
  - [x] `sqrt`
  - [x] `subtract`
  - [x] `tan`
  - [x] `tanh`
  - ~`torch_index_select`~ -> on deprecation process
  - [ ] `transpose`
  - [ ] `triangular_solve`
  - ~`tuple`~ -> on deprecation process
  - [ ] unary_einsum -> on deprecation process, but used by `Tenet`
  - [ ] `uniform_dequantize`
  - [ ] `uniform_quantize`
  - [ ] `while_`
  - [x] `xor`

- [ ] `chlo`
  - [x] `acos`
  - [x] `acosh`
  - ~`_asin_acos_kernel`~ --> should not be used `directly`
  - [x] `asin`
  - [x] `asinh`
  - [x] `atan`
  - [x] `atanh`
  - [x] `bessel_i1e`
  - [ ] `broadcast_add`
  - [ ] `broadcast_and`
  - [ ] `broadcast_atan2`
  - [ ] `broadcast_compare`
  - [ ] `broadcast_complex`
  - [ ] `broadcast_divide`
  - [ ] `broadcast_maximum`
  - [ ] `broadcast_minimum`
  - [ ] `broadcast_multiply`
  - [ ] `broadcast_next_after`
  - [ ] `broadcast_or`
  - [ ] `broadcast_polygamma`
  - [ ] `broadcast_power`
  - [ ] `broadcast_remainder`
  - [ ] `broadcast_select`
  - [ ] `broadcast_shift_left`
  - [ ] `broadcast_shift_right_arithmetic`
  - [ ] `broadcast_shift_right_logical`
  - [ ] `broadcast_subtract`
  - [ ] `broadcast_xor`
  - [ ] `broadcast_zeta`
  - [x] `conj`
  - [ ] `constant_like`
  - [ ] `constant`
  - [x] `cosh`
  - [x] `digamma`
  - [x] `erf_inv`
  - [x] `erf`
  - [x] `erfc`
  - [x] `is_inf`
  - [x] `is_neg_inf`
  - [x] `is_pos_inf`
  - [x] `lgamma`
  - [x] `next_after`
  - [x] `polygamma`
  - [x] `sinh`
  - [x] `tan`
  - [ ] `top_k`
  - [x] `zeta`

- [ ] `enzyme`
  - [ ] `addTo`
  - [ ] `autodiff`
  - [ ] `batch`
  - [ ] `fwddiff`
  - [ ] `genericAdjoint`
  - [ ] `get`
  - [ ] `init`
  - [ ] `placeholder`
  - [ ] `pop`
  - [ ] `push`
  - [ ] `set`
