### ISSUE TITLE
Tracking issue for missing tests

### ISSUE THREAD

**Issue by mofeing** [EnzymeAD/Reactant.jl#311]
- [ ] Ops
  - [ ] after_all
  - [ ] cbrt (depends on #291, spec might misspecified for complex numbers)
  - [ ] constant (depends on #196)
  - cosine on Apple x86_64 (it's a bug on a deprecated platform)
  - [ ] einsum (needs more cases)
  - [ ] iota
  - [ ] logistic
  - [ ] partition_id (depends on #196)
  - [ ] outfeed
  - [ ] recv
  - [ ] replica_id (depends on #196)
  - [ ] rng_bit_generator
  - [ ] send
  - [ ] set_dimension_size
  - [ ] zeta
